### ISSUE TITLE
feature request - please provide an option to use a cidr for the whole cluster

### ISSUE THREAD

**Issue by cameronbraid** [plunder-app/kube-vip#49]
One thing I like about metallb is that you can install it, configure it and it will work for all namespaces without having to deploy a namespace specific config as well as a deployment (kube-vip) in the namespace

Would an alternative way of deploying work where
* kube-vip is deployed as a daemonset
* there is a cidr config that is used when there is no namespace specific cidr

One downside with using a daemonset for kube-vip is that if the pod crashes it effects all vips on that node

**Comment by thebsdbox** [comment]
This is certainly something that could be done:

The replicaset for `kube-vip` has a bunch of anti-affinity rules to ensure placement for a "few" instances whilst always ensuring only a single instance per underlying node. So I'm not sure what benefit moving to a daemonset would bring other than more instances for higher availability?

The "global cidr" is a nice idea, I wanted to provide "multi-tenant" VIP ranges per namespace so that applications could sit in different ranges OR use VIPs on a different interface to other namespaces. But a fall-back CIDR range shouldn't be too complicated to implement.

**Comment by vrabbi** [comment]
Any update on this feature? A global code would be awesome and is currently a blocker for our environment for moving from metallb to kube-vip

**Comment by thebsdbox** [comment]
No worries I'll look into it this weekend. 🙂

**Comment by vrabbi** [comment]
Awesome! Thank you! This is a great project and really looking forward to using it
